### ISSUE TITLE
Using headless chrome with RSelenium

### ISSUE THREAD

**Issue by johndharrison** [ropensci/RSelenium#138]
As of chrome 59 browser can be called in headless mode

**Comment by johndharrison** [comment]
Should work on unix variants from chrome 59. Windows currently spawns a pop-up but should work from chrome 60:

```
library(RSelenium)
eCaps <- list(chromeOptions = list(
  args = c('--headless', '--disable-gpu', '--window-size=1280,800')
))
rD <- rsDriver(extraCapabilities = eCaps)
remDr <- rD$client
remDr$navigate("http://www.google.com")
remDr$screenshot(display = TRUE)
```

**Comment by clsalinas** [comment]
This is really amazing! Thanks for doing this!!
Does this have download capabilities? I am trying to download a file, and cannot seem to make it work. If you have any guidance or ideas for my code below, that would be great.
-Thanks!

library(wdman)
library(RSelenium)

cDrv <- chrome()
eCaps <- list(
  chromeOptions = list(
    args = c('--headless', '--disable-gpu', '--window-size=1280,800'),
    prefs = list(
      "profile.default_content_settings.popups" = 0L,
      "download.prompt_for_download" = FALSE,
      "download.default_directory" = "/home/csalinas/Downloads"
    )
  )
)

remDr <- remoteDriver(browserName = "chrome", port = 4567L, extraCapabilities = eCaps)
remDr$open()

co_url <- 'http://tracer.sos.colorado.gov/PublicSite/DataDownload.aspx'
remDr$navigate(co_url)

csv_link <- remDr$findElement("xpath", "//a[contains(@href, '2017_ContributionData.csv.zip')]")
csv_link$clickElement()

list.files("/home/csalinas/Downloads")

**Comment by johndharrison** [comment]
Hi @clsalinas 

Currently downloading is disabled in headless chrome see https://bugs.chromium.org/p/chromium/issues/detail?id=696481

Reading this issue downloading should be available from chrome 61+

**Comment by clsalinas** [comment]
Oh great! I will stay tuned for chrome 61

**Comment by MislavSag** [comment]
How to run headless chrome using docker?

**Comment by joshua-a-becker** [comment]
is there a way to use a port other than 4567? 

(i'm trying to load-test an app and I want to run multiple instances)

**Comment by joshua-a-becker** [comment]
whoops, solved---
```
port=4000L
chrome(port=port)
```

**Comment by juyeongkim** [comment]
@clsalinas  Add this code after creating a remoteDrive object:

```R
remDr$queryRD(
  ipAddr = paste0(remDr$serverURL, "/session/", remDr$sessionInfo[["id"]], "/chromium/send_command"),
  method = "POST",
  qdata = list(
    cmd = "Page.setDownloadBehavior",
    params = list(
      behavior = "allow",
      downloadPath = getwd()
    )
  )
)
```

This sends a command to the headless chrome to allow downloading.

I follow [this python solution](https://stackoverflow.com/a/47366981).

duplicate issue: https://github.com/ropensci/wdman/issues/19

**Comment by wjiarao** [comment]
@johndharrison Thanks for your post, I used this method, an error was occured.
Following was the code, and the system platform was Windows 7 64 bit, version of chrome  68.0.3409.2
library(RSelenium)
library(Rwebdriver)
library(wdman)
> cDrv <- chrome()
checking chromedriver versions:
BEGIN: PREDOWNLOAD
Error in open.connection(con, "rb") : 
  schannel: failed to receive handshake, SSL/TLS connection failed
################################################
###The following code can't be run.
eCaps <- list(
  chromeOptions = list(
    args = c('--headless', '--disable-gpu', '--window-size=1280,800'),
    prefs = list(
      "profile.default_content_settings.popups" = 0L,
      "download.prompt_for_download" = FALSE,
      "download.default_directory" = "/home/csalinas/Downloads"
    )
  )
)

remDr <- remoteDriver(browserName = "chrome", port = 4567L, extraCapabilities = eCaps)
remDr$open()

How can I solve this promble?
I wand to use RSelenium + head less mode of Chrome, please give me an advice? Thanks a lot.

**Comment by ponnet** [comment]
Any new solutions? Works like a charm and then breaks for headless..

**Comment by Danny-dK** [comment]
I had a script working with the queryRD part to get headless chrome downloading in a location of my choosing. I had not used the script for some time. This week I did and it failed. The first error was using the wrong chromedriver version. This tends to happen, so I looked up available chromedrivers with `binman::list_versions("chromedriver")`. I found the latest compatible for my chrome version 76 being 76.0.3809.126. I could open a headless chrome, only now when i ran the queryRD part:

`remDr1$queryRD(ipAddr = paste0(remDr1$serverURL, "/session/", remDr1$sessionInfo[["id"]], "/chromium/send_command"),
              method = "POST", qdata = list(cmd = "Page.setDownloadBehavior", params = list(behavior = "allow",
              downloadPath = "D:\\")))` 
 
It resulted in an error with a not so helpful message: Unknown Command. After looking all over for possible solutions, out of desperation I tried all 16 chromedriver versions that I had available. Turns out, certain drivers do run without problems in headless chrome with the queryRD specification, and others do not (they do however run without the queryRD). My chrome version is 76, but the queryRD part would not work unless I used one of chromedrivers "2.44", "70.0.3538.97", "71.0.3578.33", "71.0.3578.80", "71.0.3578.137", "72.0.3626.69", "72.0.3626.7". The 73 to 76 driver versions would not recognize the queryRD part but they would allow me to start a headless chrome if I did not select and run the queryRD (but then a headless chrome does not download).

Is there a different command being implemented in newer versions of chromedrivers?

**Comment by taiyodayo** [comment]
for file downloads, I resorted to using docker container from selenium hub.
https://github.com/SeleniumHQ/docker-selenium

mount the default user's download directory using the -v option like this:
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm -v ~/selenium_dl:/home/seluser/Download selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210114 

initialise remotedriver to port 4444 and RSelenium works beautifully.

**Comment by Danny-dK** [comment]
@ponnet Headless chrome downloading for me depends on the chrome driver. With newer chrome drivers, the queryRD part is not fully recognized. I'm assuming something changed in the chromedriver. See for example #211 It does work without headless, which is fine for me. I'm assumin a docker would also work as in comment of @taiyodayo above.
