### ISSUE TITLE
Null pointer exception when scrolling

### ISSUE THREAD

**Issue by fvalenduc** [ropensci/RSelenium#142]
Since a few days, I am not able anymore to scroll down with RSelenium. The problem for me is a complete mystery. I use code like this:

remDr$executeScript("window.scrollTo(0, document.body.scrollHeight)") or   remDr$executeScript(paste("scroll(0,",100000,");"))

Until a few days, it worked perfectly well. Now, it always gives the following error:

Erreur :      Summary: UnknownError
      Detail: An unknown server-side error occurred while processing the command.
      class: java.lang.NullPointerException
     Further Details: run errorDetails method

Would you have any idea about this ?
Thanks in advance for your help,
Best regards,

François

**Comment by fvalenduc** [comment]
This error was with selenium 3.4.0. With version 3.5.0, I get this:

Selenium message:unknown error: 'args' must be a list

**Comment by fvalenduc** [comment]
Changing remDr$executeScript("window.scrollTo(0, document.body.scrollHeight)") by remDr$executeScript("window.scrollTo(0, document.body.scrollHeight)", list("")) removed the null pointer exception. Still no idea why the previous version has worked for months.

**Comment by brinaseidel** [comment]
Had the same issue with code that worked before updating RSelenium. Adding list("") worked for me too. Frustrating but thanks for sharing your fix!!

**Comment by juyeongkim** [comment]
@fvalenduc this is resolved in 2c31c4fac1d8aa8a9b72ac1a06673b545dcce72a

This was due to changes in `httr` package (removing empty list in body before sending a request): [r-lib/httr@ce50e60](https://github.com/r-lib/httr/commit/ce50e60caff3430bc1f7302728e6c5131b9ae651#diff-475284c83f91b5f64ec0e4afdbd4c955R49)

Selenium was expecting `args` as a list, but in the request, `args` has been removed from body, so it was throwing that error.
