### ISSUE TITLE
RSelenium removed from CRAN

### ISSUE THREAD

**Issue by fvalenduc** [ropensci/RSelenium#172]
Everything is in the subject. Packages wdman, binman and RSelenium have been removed from CRAN. Can you explain why ? 
Is it possible to put the packages on CRAN again ?

**Comment by FabianFox** [comment]
@fvalenduc 
That does not directly address the issue but you can install the archived packages which did work for me under R 3.5.0.  

```r
library(devtools)
install_version("binman", version = "0.1.0", repos = "https://cran.uni-muenster.de/")
install_version("wdman", version = "0.2.2", repos = "https://cran.uni-muenster.de/")
install_version("RSelenium", version = "1.7.1", repos = "https://cran.uni-muenster.de/")
````
See the following [information](https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages) at RStudio for installing archived packages.

**Comment by fvalenduc** [comment]
It  seems RSelenium has been removed because it depends on binman and wdman which both would have checks problems. I don't understand why RSelenium has these dependencies. It seems that these packages only serves to download the selenium jar file or utilities like chromedriver or geckodriver. This can be done manually very easily and is also not needed when using docker. Furthermore, chromedriver is packaged for a lot of distributions.

**Comment by alistaire47** [comment]
You can also install them all from GitHub:
```r
devtools::install_github("johndharrison/binman")
devtools::install_github("johndharrison/wdman")
devtools::install_github("ropensci/RSelenium")
```
Order matters.

**Comment by fvalenduc** [comment]
Seeing the absence of reaction of the author of Rselenium, I am wondering if this package is still maintained ? I hope so, because we use it everyday in production system for the computation of official statistics.

**Comment by JBGruber** [comment]
Following @methodds  suggestion, I created PR #177 .  @fvalenduc  already laid out exactly what to do. However, all the `testthat` tests fail. Locally as well as on travis. Running my own scripts with the altered package and without `wdman` and `binman` installed on my system works fine, however.

**Comment by methodds** [comment]
Awesome, thanks :)

**Comment by juyeongkim** [comment]
Hello all! I have taken over the maintainership over `RSelenium` and its related packages. I've fixed the test errors for `wdman` and `binman` and submitted back to CRAN, and now I'm fixing `RSelenium` and plan to submit it back to CRAN soon. Many of these errors are due to the changes in the dependencies (`httr`, `testthat`, etc), and some are due to the minor changes in the webdrivers.

I understand your frustration as I also use the package in production, but I am really excited to work on this project because many people use this package and contributed by answering each other's questions while the maintainer was absent. This is an intricate project, and I do not know the solutions to every issue, so I am open to discuss and implement any suggestions and PR you might have. Thank you for being patient, and thank you for using RSelenium! :)

**Comment by yerovi84** [comment]
Hi, I'm trying to install Rselenium and give me the following error:

 "ERROR: dependencies 'caTools', 'openssl' are not available for package 'RSelenium'
* removing 'C:/Users/rayerovi/Documents/R/R-3.5.0/library/RSelenium'
In R CMD INSTALL
Installation failed: Command failed (1)"

**Comment by juyeongkim** [comment]
@yerovi84 do you have `caTools` and `openssl` packages installed?

**Comment by yerovi84** [comment]
Yes I do, but I forgot to reboot r session.

Sorry and thanks for answer.

**Comment by asinofsky** [comment]
Hey, I'm a programming noob that's been relying on RSelenium for a bit and I can't get it to install now. My code stopped working with the new firefox so I thought I'd update my RSelenium since it's been a bit and see if that magically fixed things. Sadly, when I tried to run the code to update it, the install failed and it removed my old RSelenium and now I can't get it to reinstall. 

I'm trying to follow the directions here but I can't get binman to install. I tried going through the R terminal output and figured out a few things it depends on that were out of date and updated those, but now I'm stuck on:

-llzma -liconv -lz -lws2_32 -Ld:/RCompile/r-compiling/local/local320/lib/i386 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.2/bin/i386 -lR
c:/rbuildtools/3.3/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -liconv
c:/rbuildtools/3.3/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lz
collect2: ld returned 1 exit status
no DLL was created

I tried googling for "R liconv" and couldn't find much of anything. What should I do?

**Comment by juyeongkim** [comment]
@asinofsky Sorry to hear that. Where is the installation failing exactly? Could you open an issue with the full R terminal output?

**Comment by juyeongkim** [comment]
For others, I plan to submit RSelenium to CRAN on 10th. (CRAN team is on vacation til 9th)

**Comment by Mthrun** [comment]
How did the submission to CRAN go?

**Comment by juyeongkim** [comment]
RSelenium is back on CRAN now! :champagne:
